### ISSUE TITLE
Sandboxed Evince crashes when trying to open a volume

### ISSUE THREAD

**Issue by intrigeri** [subgraph/oz#86] opened 2016-10-17 00:41 UTC
1. Start sandboxed Evince by double-clicking a PDF in Files
2. Click the hamburger icon -> Open
3. Click "boot" in the left sidebar
4. Evince disappears

The Journal says:

<pre>
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (stderr) **
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (stderr) GLib-GIO:ERROR:/build/glib2.0-2.49.6/./gio/gunixvolume.c:319:eject_mount_do: assertion fail
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] Child process pid=56 exited from init with status -1
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] Shutting down sandbox after child exit.
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,766 New unix-domain connection received on /home/toto/.Xoz/evince/
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,773 Connection lost
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,774 New unix-domain connection received on /home/toto/.Xoz/evince/
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,795 Python2/GObject client version 0.17.5-r13454
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,795  connected from 'evince' as 'toto'
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,798 Shutting down in response to client request
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,798 Disconnecting client /home/toto/.Xoz/evince/evince-0:
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,798  server shutdown
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-client-stderr) 2016-10-17 02:38:33,800 server requested disconnect: server shutdown
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,807 Disconnecting client /home/toto/.Xoz/evince/evince-0:
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,826  server shutdown
Oct 17 02:38:33 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:33 [evince] (xpra-server) 2016-10-17 02:38:33,830 xpra client disconnected.
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 Child process pid=4886 exited from daemon with status 0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 No sandbox found with oz-init pid = 4886
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] (xpra-server) 2016-10-17 02:38:34,832 xpra is terminating.
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] (xpra-server) 2016-10-17 02:38:34,833 removing socket /home/toto/.Xoz/evince/evince-0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] (xpra-server) 2016-10-17 02:38:34,834 killing xvfb with pid 22
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] (xpra-server) (II) Server terminated successfully (0). Closing log file.
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] (xpra stop) xpra at :0 has exited.
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] Child process pid=10 exited from init with status 0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] Child process pid=34 exited from init with status 0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] Child process pid=70 exited from init with status 0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] Child process pid=77 exited from init with status 1
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] Child process pid=85 exited from init with status 0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] Child process pid=103 exited from init with status 0
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 [evince] oz-init exiting...
Oct 17 02:38:34 sid-desktop oz-daemon[2633]: 2016/10/17 02:38:34 Child process pid=4830 exited from daemon with status 0
</pre>

On the host system, `/boot` is a separate partition.
I guess it's a common problem of software assuming they can access various things that the OZ sandbox prevents. I have no clue how this could be solved in a way that provides a nicer UX.

**Comment by xSmurf** [comment] 2016-10-17 14:14
This seems like a seccomp hit, do you have audit logs?

**Comment by intrigeri** [comment] 2016-10-24 11:05
I see one entry in `/var/log/audit/audit.log` at the time of the crash:

<pre>
type=ANOM_ABEND msg=audit(1477307062.982:22): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=3389 comm="evince" exe="/usr/bin-oz/evince" sig=6
</pre>

If that's not what you need, please let me know what I should do to gather the info you want :)

**Comment by xSmurf** [comment] 2016-11-03 16:18
Just had a look again, I'm not sure where evince fetches this list of disks but it's really pulling out of it's own behind. It references mount that don't exist (/boot for example), so I'm not particularly surprised it chokes trying to mount some disks.

The log output above was truncated, here's the complete error:

> GLib-GIO:ERROR:/build/glib2.0-H0dUFE/glib2.0-2.50.0/./gio/gunixvolume.c:319:eject_mount_do: assertion failed (error == NULL): Failed to execute child process "mount" (Permission denied)

Yep, mount is not available to you Evince, and this is by design. As such I'll close this issue.

**Closed by xSmurf** 2016-11-03 16:18 UTC

**Comment by xSmurf** [comment] 2016-11-03 17:40
Indeed blacklisting /etc/fstab seems to fix the gio confusion. So far with no adverse effects, but I'll keep testing for a bit.
