### ISSUE TITLE
Missing dependency on resolvconf

### ISSUE THREAD

**Issue by intrigeri** [subgraph/oz#83] opened 2016-10-17 00:09 UTC
Hi!

on a Debian sid system, I've installed an oz package built today following the instructions in README, run `oz-setup install evince`, and double-clicked a PDF file in Files (Nautilus). GNOME let me know for a few seconds that the app was starting, and then nothing happened.

The Journal says:

<pre>
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] Starting oz-init for profile: evince
Oct 17 02:04:21 sid-desktop nautilus[3315]: Error creating thumbnail for file:///home/toto/Downloads/autotools.pdf: Unrecognized image file format
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] bind mounting (as readonly) /bin -> /srv/oz/rootfs/bin
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] bind mounting (as readonly) /lib -> /srv/oz/rootfs/lib
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] bind mounting (as readonly) /lib64 -> /srv/oz/rootfs/lib64
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] bind mounting (as readonly) /usr -> /srv/oz/rootfs/usr
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] bind mounting (as readonly) /etc -> /srv/oz/rootfs/etc
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 [evince] Failed to setup filesytem: failed to create empty directory '/run/resolvconf': stat /run/resolvconf: no such file or directory
Oct 17 02:04:21 sid-desktop oz-daemon[2633]: 2016/10/17 02:04:21 Child process pid=3375 exited from daemon with status 1
</pre>

So I've installed resolvconf and my next attempt did not fail due to a missing `/run/resolvconf`.

Perhaps this dependency should be encoded in `debian/control`?

**Comment by xSmurf** [comment] 2016-10-17 14:19
As you saw, this is a duplicate of #81.

**Closed by xSmurf** 2016-10-17 14:19 UTC
